nutanix_username        = "user name"
nutanix_password        = "Password"
nutanix_endpoint        = "IP Address of Prism Central"
nutanix_network_name    = "Secondary VLN Name here"
nutanix_vlan_number     = "VLAN ID Number here"
nutanix_gateway_ip      = "Enter the Default Gateway IP Here" 
nutanix_subnet_ip       = "Enter he Subnet IP Scheme Here"
nutanix_dns_server_name = "Enter Auto DC VM IP Address Here"